import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Re-seeds the four system roles and their permission sets after the UUID v7
 * migration (1700000000400) truncated all tables.
 *
 * Role data is identical to what was originally inserted in
 * 1700000000300-RolesAndPermissions.ts, but PKs are now generated by
 * the native uuidv7() function.
 */
export class ReseedSystemRoles1700000000500 implements MigrationInterface {
  name = 'ReseedSystemRoles1700000000500';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const roles: Array<{ name: string; description: string; permissions: string[] }> = [
      {
        name: 'customer',
        description: 'Vehicle owner who books wash services',
        permissions: [
          'users:read.self',
          'users:write.self',
          'vehicles:manage.self',
          'bookings:create',
          'bookings:read.self',
          'bookings:cancel',
          'payments:read.self',
          'reviews:create',
          'reviews:read',
          'photos:read',
        ],
      },
      {
        name: 'vendor',
        description: 'Detailing professional who fulfils assigned jobs',
        permissions: [
          'users:read.self',
          'users:write.self',
          'bookings:read.assigned',
          'bookings:transition',
          'photos:upload',
          'photos:read',
          'reviews:read',
        ],
      },
      {
        name: 'admin',
        description: 'Operations admin: vendor matching, payouts, dispute handling',
        permissions: [
          'users:read.self',
          'users:write.self',
          'users:read.all',
          'users:write.all',
          'roles:read',
          'vehicles:read.all',
          'bookings:read.all',
          'bookings:assign-vendor',
          'bookings:cancel',
          'payments:read.all',
          'payments:refund',
          'payments:payout',
          'photos:read',
          'reviews:read',
        ],
      },
      {
        name: 'super_admin',
        description: 'Unrestricted access; can manage roles and permissions',
        permissions: ALL_PERMISSIONS,
      },
    ];

    for (const role of roles) {
      await queryRunner.query(
        `INSERT INTO "roles" ("name", "description", "is_system") VALUES ($1, $2, true)`,
        [role.name, role.description],
      );
      for (const perm of role.permissions) {
        await queryRunner.query(
          `INSERT INTO "role_permissions" ("role_id", "permission")
           SELECT "role_id", $2 FROM "roles" WHERE "name" = $1`,
          [role.name, perm],
        );
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM "roles" WHERE "name" IN ('customer', 'vendor', 'admin', 'super_admin') AND "is_system" = true`,
    );
  }
}

const ALL_PERMISSIONS: string[] = [
  'users:read.self',
  'users:write.self',
  'users:read.all',
  'users:write.all',
  'roles:read',
  'roles:manage',
  'roles:assign',
  'vehicles:manage.self',
  'vehicles:read.all',
  'bookings:create',
  'bookings:read.self',
  'bookings:read.assigned',
  'bookings:read.all',
  'bookings:assign-vendor',
  'bookings:transition',
  'bookings:cancel',
  'payments:read.self',
  'payments:read.all',
  'payments:refund',
  'payments:payout',
  'photos:upload',
  'photos:read',
  'reviews:create',
  'reviews:read',
];
